#
# Makefile for linux kernel
#
obj-$(CONFIG_EFI)			+= efi.o vars.o reboot.o
obj-$(CONFIG_EFI_VARS)			+= efivars.o
obj-$(CONFIG_EFI_VARS_PSTORE)		+= efi-pstore.o
obj-$(CONFIG_UEFI_CPER)			+= cper.o
obj-$(CONFIG_EFI_RUNTIME_MAP)		+= runtime-map.o
obj-$(CONFIG_EFI_RUNTIME_WRAPPERS)	+= runtime-wrappers.o
obj-$(CONFIG_EFI_STUB)			+= libstub/
obj-$(CONFIG_EFI_PARAMS_FROM_FDT)	+= efi-fdt.o

disabled-obj-$(CONFIG_XEN)	:= reboot.o
